name: adguard_home_client
description: "A remote for AdGuard Home instances."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.10
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon/app_icon.png"
  adaptive_icon_foreground: "assets/images/icon/app_icon_adaptive.png"
  adaptive_icon_background: "assets/images/icon/app_icon_adaptive.png"
  adaptive_icon_foreground_inset: 0
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
