swagger_parser:
  schema_path: assets/openapi.yaml
  output_directory: lib/generated_api
  language: dart
  squish_clients: true
  client_postfix: Api
  include_paths:
    - /status
    - /protection
    - /dns_info
    - /stats
    - /stats_info
    - /stats_reset
    - /stats/config
    - /stats/config/update
    - /safebrowsing/status
    - /safebrowsing/enable
    - /safebrowsing/disable
    - /parental/status
    - /parental/enable
    - /parental/disable
    - /safesearch/status
    - /safesearch/settings
    - /querylog
    - /querylog_clear
    - /querylog/config
    - /querylog/config/update
    - /blocked_services/all
    - /blocked_services/services
    - /blocked_services/get
    - /blocked_services/set
    - /blocked_services/update
    - /filtering/status
    - /filtering/set_rules
    - /filtering/add_url
    - /filtering/remove_url
    - /filtering/set_url
    - /filtering/refresh
    - /dns_config
    - /cache_clear
    - /test_upstream_dns
    - /rewrite/list
    - /rewrite/add
    - /rewrite/delete
    - /rewrite/update
    - /clients
    - /clients/add
    - /clients/delete
    - /clients/update
